receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 10
    sampling_thereafter: 1000
  otlphttp:
    traces_endpoint: https://xray.${REGION}.amazonaws.com/v1/traces
    compression: gzip
    auth:
      authenticator: sigv4auth
extensions:
  sigv4auth:
    region: "${REGION}"
    service: "xray"

service:
  telemetry:
    logs:
      level: "debug"
  extensions: [sigv4auth]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, debug]