spring:
  application:
    name: admin-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

eureka:
  instance:
    preferIpAddress: true
    ipAddress: ${ADMIN_IP:admin-server}
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://discover-server:8761/eureka/}
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:${CONFIG_SERVER_URL:http://config-server:8888}