apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nutrition-service-nodejs
  name: nutrition-service-nodejs
spec:
  ports:
    - name: '80'
      port: 80
      targetPort: 3000
  selector:
    io.kompose.service: nutrition-service-nodejs
status:
  loadBalancer: {}
