# Generated by Django 5.0.3 on 2024-03-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_id", models.IntegerField()),
                ("type", models.CharField(max_length=200)),
                ("type_name", models.CharField(max_length=200)),
                ("pet_id", models.IntegerField()),
                ("payment", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(max_length=20)),
            ],
            options={
                "unique_together": {("owner_id", "pet_id", "type")},
            },
        ),
    ]
