# Generated by Django 4.2.16 on 2024-11-07 22:51

from django.db import migrations, models
import random

def generate_random_string():
    return ''.join(random.choices('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', k=32))

def fill_check_list(apps, schema_editor):
    CheckList = apps.get_model('billing_service', 'CheckList')

    # Generate 1/10 million rows in batches
    batch_size = 10000
    for i in range(0, 100000, batch_size):
        batch = [
            CheckList(
                id=j,
                invalid_name=generate_random_string()
            )
            for j in range(i, min(i + batch_size, 100000))
        ]
        CheckList.objects.bulk_create(batch)

class Migration(migrations.Migration):

    dependencies = [
        ('billing_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invalid_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'check_list',
            },
        ),
        migrations.RunPython(fill_check_list),
    ]
