# Generated by Django 4.2.16 on 2024-11-07 22:51

from django.db import migrations
import random

def generate_random_string():
    return ''.join(random.choices('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', k=32))

def fill_check_list(apps, schema_editor):
    CheckList = apps.get_model('billing_service', 'CheckList')

    # Generate 1 million rows in batches
    batch_size = 10_000
    total_rows = 1_000_000
    for i in range(0, total_rows, batch_size):
        batch = [
            CheckList(
                id=j,
                invalid_name=generate_random_string()
            )
            for j in range(i, min(i + batch_size, total_rows))
        ]
        CheckList.objects.bulk_create(batch, ignore_conflicts=True)

class Migration(migrations.Migration):

    dependencies = [
        ('billing_service', '0002_checklist'),
    ]

    operations = [
        migrations.RunPython(fill_check_list),
    ]
