# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (HEAD)
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  ports:
    - port: 27017
  selector:
    io.kompose.service: mongodb
status:
  loadBalancer: {}

